name: dartapi
description: DartAPI A lightweight, FastAPI-inspired framework for building scalable, high-performance REST APIs in Dart with built-in routing, middleware, and CLI support.
version: 0.0.5
repository: https://github.com/akashgk/dartapi
homepage: https://github.com/akashgk/dartapi
issue_tracker: https://github.com/akashgk/dartapi/issues

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  test: ^1.22.0
  lints: ^5.1.1

executables:
  dartapi: dartapi
