name: dartapi
description: >
  DartAPI is a CLI-driven project generator and toolset for building typed REST APIs in Dart.
  It provides modular packages for authentication, database access, request validation, and controller-based routing.
  Ideal for developers who want structure, but not a full framework.
version: 0.1.3
repository: https://github.com/akashgk/dartapi
homepage: https://github.com/akashgk/dartapi
issue_tracker: https://github.com/akashgk/dartapi/issues

environment:
  sdk: ^3.7.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  test: ^1.22.0
  lints: ^5.1.1

executables:
  dartapi:
